FROM jboss/base-jdk:8

ENV VERTICLE_FILE vertx-server.jar

ENV VERTICLE_HOME /opt/jboss
ENV vertx.cacheDirBase $VERTICLE_HOME
ENV VERTX_CHE_SERVER_URL=http://localhost:33333
ENV VERTX_OS_ROUTE_HOST=localhost:33333
ENV VERTX_OS_PROJECT=che

EXPOSE 33333
  
COPY target/$VERTICLE_FILE $VERTICLE_HOME/

USER root

RUN chgrp -R 0 $VERTICLE_HOME \
  && chmod -R g+rwX $VERTICLE_HOME

USER jboss

WORKDIR $VERTICLE_HOME

ENTRYPOINT ["sh", "-c"]
CMD ["exec java -jar $VERTICLE_FILE"]